version: "3.8"
services:
  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    restart: unless-stopped
    working_dir: /home/dynamodblocal
    volumes:
      - ./data:/home/dynamodblocal/data
    ports:
      - "8000:8000"

