version: "3.8"
services:
  mysql:
    image: mysql
    container_name: mysql-local
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
